### ISSUE TITLE
Testing Instructions

### ISSUE THREAD

**Issue by capt-hb** [CTSRD-CHERI/sail-cheri-mips#22]
I'm currently working on sail-cheri-mips for a project and have modified some instructions and might also add some instructions later on (in my fork of the project).
Currently I'm stuck with how to actually test the CHERI instructions. Would it be possible to give some information about how to do this?

**Comment by rmn30** [comment]
Hello. The Cheri tests are actually in a separate repository that is not public at the moment. Perhaps @rwatson could advise further. I'm actually on holiday at the moment!

**Comment by rwatson** [comment]
I believe that the required tests are located at https://github.com/CTSRD-CHERI/cheritest (for ISA-level testing, modest compiler stuff) and https://github.com/CTSRD-CHERI/cheri-c-tests (further C-level tests). Full integration testing using CheriBSD offers more complete compiler coverage, and its 'cheritest' and 'cheriabitest' command-line tools exercise quite a few architecture, compiler, linker, and OS features relating to CHERI.

**Comment by capt-hb** [comment]
Thanks, that helps me a lot!
