### ISSUE TITLE
Revert 76fbfd4e2f3dc17abee7c54d035e551b74400fb9?

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/sail-cheri-mips#7]
With 76fbfd4e2f3dc17abee7c54d035e551b74400fb9 in place, I'm told

```
sail -latex -latex_prefix sailcc -o sail_latexcc ../mips/prelude.sail cheri_types.sail cheri_prelude_128.sail
Syntax error at file "../mips/prelude.sail", line 119, character 132:

val min_atom = {ocaml: "min_int", lem: "min", coq: "min_atom", c:"min_int"} : forall 'a 'b . (atom('a), atom('b)) -> {'c, ('c == 'a | 'c == 'b) & 'c <= 'a & 'c <= 'b . atom('c)}

no information
```

but reverting it lets the build to through just fine.  (Character 132 is the `|` on that line; the terminal coloration doesn't copy-paste well.)

**Comment by rmn30** [comment]
This is due to new syntax in dev. version of sail. You need to either build sail from git or I could release a new opam package.

**Comment by rmn30** [comment]
Or you could use opam to 'pin' to dev repo thusly:
```
git clone https://github.com/rems-project/sail
cd sail
opam pin add sail .
```

**Comment by arichardson** [comment]
Or you could use `cheribuild.py sail-from-opam --sail-from-opam/use-git-version`

**Comment by nwf** [comment]
Thanks!

**Comment by rmn30** [comment]
In future we might be more careful about synchronising sail package releases and sail-cheri-mips updates...
